<?php

/**
 *
 * @file
 * Primary module hooks for Booking Manager module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */
use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeTypeInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\node\Entity\NodeType;
use Stephane888\Debug\debugLog;

/**
 * Implements hook_theme().
 */
function booking_manager_theme() {
  $theme = [];
  $theme['manage_days_entity'] = [
    'render element' => 'elements',
    'file' => 'manage_days_entity.page.inc',
    'template' => 'manage_days_entity'
  ];
  //
  $theme['manage_days_entity_content_add_list'] = [
    'render element' => 'content',
    'variables' => [
      'content' => NULL
    ],
    'file' => 'manage_days_entity.page.inc'
  ];
  //
  $theme['booking_manager_horaire'] = [
    'render element' => 'content',
    'variables' => [
      'content' => NULL
    ],
    'file' => 'booking_manager.inc'
  ];
  //
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function booking_manager_theme_suggestions_manage_days_entity(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#manage_days_entity'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');
  //
  $suggestions[] = 'manage_days_entity__' . $sanitized_view_mode;
  $suggestions[] = 'manage_days_entity__' . $entity->bundle();
  $suggestions[] = 'manage_days_entity__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'manage_days_entity__' . $entity->id();
  $suggestions[] = 'manage_days_entity__' . $entity->id() . '__' . $sanitized_view_mode;
  //
  return $suggestions;
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function booking_manager_form_node_type_form_alter(&$form, FormStateInterface $form_state) {
  $form['prise_rdv'] = array(
    '#type' => 'details',
    '#title' => t(' Prise de rendez vous '),
    '#group' => 'additional_settings'
  );

  // Load the current node type configuration entity.
  $node_type = $form_state->getFormObject()->getEntity();

  $form['prise_rdv']['booking_manager_enabled'] = array(
    '#type' => 'checkbox',
    '#title' => t('Enable reusable forms'),
    '#description' => t('Check this box if you would like a reusable form on this node type.'),
    '#default_value' => $node_type->getThirdPartySetting('booking_manager', 'enabled', 0)
  );
  //
  $form_plugins = \Drupal::service('plugin.manager.booking_manager.manage_days')->getDefinitions();
  $options = [];
  foreach ($form_plugins as $name => $plugin) {
    $options[$name] = $plugin['title'];
  }

  //
  $form['prise_rdv']['booking_manager_plugin'] = [
    '#type' => 'radios',
    '#title' => t('Available forms'),
    '#default_value' => $node_type->getThirdPartySetting('booking_manager', 'plugin', 'default_model'),
    '#options' => $options,
    '#description' => t('The available forms you can choose from for this node type.'),
    '#states' => [
      'visible' => [
        ':input[name="booking_manager_enabled"]' => [
          'checked' => TRUE
        ]
      ]
    ]
  ];

  /**
   * --
   */
  // $form['prise_rdv']['manage_dates'] = [
  // '#type' => 'fieldset',
  // '#title' => 'Configuration des dates',
  // '#tree' => TRUE,
  // '#states' => [
  // 'visible' => [
  // ':input[name="booking_manager_enabled"]' => [
  // 'checked' => TRUE
  // ]
  // ]
  // ]
  // ];

  // $id = 'node_' . $node_type->get('type');
  // $type =
  // \Drupal::entityTypeManager()->getStorage('manage_days_entity_type')->load($id);
  // $jours = Drupal\booking_manager\ManageDaysInterface::jours;
  // if (!empty($type)) {
  // $jours = $type->get('jours');
  // }
  // /**
  // * --
  // */
  // foreach ($jours as $i => $val) {
  // //
  // $form['prise_rdv']['manage_dates'][$i] = [
  // "#type" => 'details',
  // '#title' => $val['label'],
  // '#open' => false
  // ];
  // $form['prise_rdv']['manage_dates'][$i]['label'] = [
  // "#type" => 'textfield',
  // '#title' => 'Label',
  // '#default_value' => $val['label']
  // ];
  // //
  // $form['prise_rdv']['manage_dates'][$i]['status'] = [
  // "#type" => 'checkbox',
  // '#title' => 'Status',
  // '#default_value' => $val['status']
  // ];
  // //
  // $form['prise_rdv']['manage_dates'][$i]['h_d__m_d'] = [
  // "#type" => 'textfield',
  // '#title' => 'Heure debut',
  // '#default_value' => $val['h_d'] . ':' . $val['m_d']
  // ];
  // //
  // $form['prise_rdv']['manage_dates'][$i]['h_f__m_f'] = [
  // "#type" => 'textfield',
  // '#title' => 'Heure fin',
  // '#default_value' => $val['h_f'] . ':' . $val['m_f']
  // ];
  // }
  //
  $form['#entity_builders'][] = 'booking_manager_form_node_type_form_builder';
  //
}

/**
 * Entity form builder for the node type form to map some values to third party
 * settings
 */
function booking_manager_form_node_type_form_builder($entity_type, NodeTypeInterface $type, &$form, FormStateInterface $form_state) {
  if ($form_state->getValue('booking_manager_enabled') === 1) {
    $type->setThirdPartySetting('booking_manager', 'enabled', 1);
    $type->setThirdPartySetting('booking_manager', 'plugin', $form_state->getValue('booking_manager_plugin'));
    // // $values['jours'] = $form_state->getValue('manage_dates');
    // $values['id'] = 'node_' . $form_state->getValue('type');
    // $values['label'] = 'Node ' . $form_state->getValue('name');
    // /**
    // *
    // * @var \Drupal\booking_manager\ManageDaysPluginManger $plugin_manager
    // */
    // $plugin_manager =
    // \Drupal::service('plugin.manager.booking_manager.manage_days');
    // /**
    // *
    // * @var \Drupal\booking_manager\ManageDaysBase $manage_days
    // */
    // $manage_days =
    // $plugin_manager->createInstance($form_state->getValue('booking_manager_plugin'));
    // $manage_days->saveTypeByArray($values);
    return;
  }
  //
  $type->unsetThirdPartySetting('booking_manager', 'enabled');
  $type->unsetThirdPartySetting('booking_manager', 'plugin');
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function booking_manager_form_node_form_alter(&$form, FormStateInterface $form_state) {
  /**
   *
   * @var \Drupal\node\NodeForm $entity
   */
  $FormObject = $form_state->getFormObject();
  /**
   *
   * @var \Drupal\node\Entity\Node $entity
   */
  $entity = $FormObject->getEntity();
  $nodeType = \Drupal\node\Entity\NodeType::load($entity->getType());
  $ThirdPartySettings = $nodeType->getThirdPartySettings('booking_manager');
  /**
   * On ajoute un bouton dans le formulaire afin de permettre de rediriger vers
   * une page d'edition de rdv.
   */
  if (!empty($ThirdPartySettings['enabled']) && !empty($ThirdPartySettings['plugin'])) {
    $form['actions']['sava_redirect_rdv'] = $form['actions']['submit'];
    $form['actions']['sava_redirect_rdv']['#submit'][] = '_booking_manager_submitRedirectRdvForm';
    $form['actions']['sava_redirect_rdv']['#value'] = 'Enregistrer et gerer le RDV';
  }
}

function _booking_manager_submitRedirectRdvForm(&$form, FormStateInterface $form_state) {
  /**
   *
   * @var \Drupal\node\NodeForm $nodeForm
   */
  $nodeForm = $form_state->getFormObject();
  // on empeche drupal de faire une redirection via destination.
  \Drupal::request()->query->remove('destination');
  $form_state->setRedirect("booking_manager.manager", [
    'entity_type_id' => 'node',
    'id' => $nodeForm->getEntity()->id()
  ]);
}

/**
 * Implements hook_entity_extra_field_info().
 */
function booking_manager_entity_extra_field_info() {
  $extra = array();
  $bundles = NodeType::loadMultiple();
  $bundles = array_filter($bundles, function ($bundle) {
    return $bundle->getThirdPartySetting('booking_manager', 'enabled') === 1;
  });

  /**
   * --
   */
  foreach ($bundles as $bundle) {
    $extra['node'][$bundle->Id()]['display']['booking_manager'] = [
      'label' => t('Prise de RDV'),
      'description' => t('Prise de RDV'),
      'weight' => 100,
      'visible' => TRUE
    ];
  }
  //
  return $extra;
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function booking_manager_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($display->getComponent('booking_manager')) {
    $plugin_manager = \Drupal::service('plugin.manager.booking_manager.manage_days');
    $node_type = NodeType::load($entity->bundle());
    $plugin = $node_type->getThirdPartySetting('booking_manager', 'plugin');
    if (!$plugin) {
      return;
    }
    // $build['booking_manager'] =
    // $plugin_manager->createInstance($plugin)->buildForm($entity);
  }
}

