booking_manager.manage_days_entity_type.*:
  type: config_entity
  label: 'Manage days entity type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    jours:
      type: mapping
      label: 'Liste de jour de la semaine'
    disabled_dates:
      type: mapping
      label: 'Liste de jour de la semaine'
    disabled_periode:
      type: mapping
      label: 'Liste de jour de la semaine'
    interval:
      type: integer
      label: "interval/durée d'un creneau"
    decallage:
      type: integer
      label: " Decallage entre deux creneaux"
    number_week:
      type: integer
      label: " Nombre de semaine à afficher "
    limit_reservation:
      type: integer
      label: " Nombre de reservation par creneaux "
      
node.type.*.third_party.booking_manager:
  type: mapping
  label: 'Prise de RDV'
  mapping:
    booking_manager_enabled:
      type: boolean
      label: 'Whether to enable the reusable forms on this node type'
    booking_manager_plugin:
      type: sequence
      label: 'Available forms'
      sequence:
        type: string
        label: 'Plugin name' 